apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hwc_cce_demo.fullname" . }}-app-secret
  namespace: {{ .Values.namespace }}
type: IngressTLS
data:
  tls.crt: {{ .Files.Get "certs/server.crt" | b64enc }}
  tls.key: {{ .Files.Get "certs/server.key" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hwc_cce_demo.fullname" . }}-db-obs-secret
  namespace: {{ .Values.namespace }}
  labels:
    secret.kubernetes.io/used-by: csi
type: cfe/secure-opaque
data:
  access.key: {{ .Files.Get "accesskey/ak" | b64enc }}
  secret.key: {{ .Files.Get "accesskey/sk" | b64enc }}