apiVersion: v1
kind: Service
metadata:
  name: {{ include "hwc_cce_demo.fullname" . }}-app-np-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.labels.app.app }}
  ports:
    - port: {{ .Values.nodeports.app.port }}
      targetPort: {{ .Values.nodeports.app.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hwc_cce_demo.fullname" . }}-db-np-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.database.app }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.nodeports.database.grpcPort }}
    targetPort: {{ .Values.nodeports.database.grpcPort }}
    name: grpc
  - port: {{ .Values.nodeports.database.httpPort }}
    targetPort: {{ .Values.nodeports.database.httpPort }}
    name: http
  selector:
    app: {{ .Values.labels.database.app }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hwc_cce_demo.fullname" . }}-db-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.database.app }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: "_status/vars"
    prometheus.io/port: "8080"
spec:
  ports:
  - port: {{ .Values.nodeports.database.grpcPort }}
    targetPort: {{ .Values.nodeports.database.grpcPort }}
    name: grpc
  - port: {{ .Values.nodeports.database.httpPort }}
    targetPort: {{ .Values.nodeports.database.httpPort }}
    name: http
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: {{ .Values.labels.database.app }}